platform: ntc
sensor: temp_resistance_reading
name: ${devicename} Temperatur
unit_of_measurement: "°C"
accuracy_decimals: 1
icon: "mdi:thermometer"
calibration:
  b_constant: 3350
  reference_resistance: 10kOhm
  reference_temperature: 298.15K
on_value_range:
  - above: ${max_temp}
    then:
      - switch.turn_off: shelly_relay_1
      - switch.turn_off: shelly_relay_2
      - homeassistant.service:
          service: persistent_notification.create
          data:
            title: Nachricht von ${devicename}
          data_template:
            message: Deaktiviert weil Temperatur Limit von ${max_temp}°C überschritten
