esphome:
  name: ${devicename}

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

uart:
  id: uart_bus
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus
